version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18.16  # Use a compatible Node.js image
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Tests with Jest
          command: npm run test -- --watch=false --no-progress

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build Angular Project
          command: npm run build -- --configuration production
      - persist_to_workspace:
          root: dist
          paths:
            - .

  deploy:
    docker:
      - image: atmoz/sftp  # Minimal SFTP Docker image
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy via SFTP
          command: |
            apk add openssh-client  # Install SSH client
            scp -r ~/workspace/* username@your-server-ip:/path/to/deployment

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

