version: 2.1

executors:
  node-executor:
    docker:
      - image: node:20-alpine
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Angular CLI and Dependencies
          command: |
            npm install -g @angular/cli
            npm install
      - run:
          name: Build Angular Project
          command: |
            rm -f .env && ln -s .env.production .env 
            ng build --configuration production
      - persist_to_workspace:
          root: dist
          paths:
            - .

  deploy:
    docker:
      - image: ubuntu:22.04
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install Required Tools
          command: |
            apt-get update && apt-get install -y openssh-client zip
      - run:
          name: Add SSH Key to Agent
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H -p 11200 $SFTP_HOST >> ~/.ssh/known_hosts
      - run:
          name: Create ZIP File
          command: |
            cd ~/workspace
            zip -r deployment.zip .  # Create a zip file of all workspace contents
      - run:
          name: Upload ZIP File
          command: |
            scp -P 11200 ~/workspace/deployment.zip albert@103.127.138.209:/home/albert/www
      - run:
          name: Extract on Remote Server
          command: |
            ssh -p 11200 albert@103.127.138.209 "unzip -o /home/albert/www/deployment.zip -d /home/albert/www && rm /home/albert/www/deployment.zip"

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
